[package]
name = "pretty-ls"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "pls"
path = "src/main.rs"

[dependencies]
comfy-table = { version = "8.0.0", features = ["custom_styling"] }
clap = { version = "4", features = ["derive"] }
ignored = "0.0.6"
phf = { version = "0.14.0", features = ["macros"] }
users = "0.11"
